# Change these first
owner: SimLive-Radio # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Webseite
    url: https://www.simliveradio.net
  - name: Helpdesk
    url: https://help.simliveradio.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: simlive-radio.github.io
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SimLiveRadio Status Page
  introTitle: "SimLiveRadio Status Page"
  introMessage: Wie geht es unseren Systemen.
  navbar:
    - title: Status
      href: /
    - title: Webseite
      href: https://simliveradio.net/
    - title: Radio
      href: https://laut.fm/simliveradio

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
